FROM twoyang0917/ubuntu

RUN \
  apt-get update && \
  apt-get install -y openjdk-7-jdk && \
  rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME /usr/lib/jvm/java-7-openjdk-amd64

CMD ["tail", "-f", "/etc/hosts"]
